In [24]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('Data-Collisions3.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [28]:
data.columns

Index(['SEVERITYCODE', 'X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO',
       'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
       'EXCEPTRSNDESC', 'SEVERITYCODE2', 'SEVERITYDESC', 'COLLISIONTYPE',
       'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE',
       'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE', 'SDOT_COLDESC',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SDOTCOLNUM', 'SPEEDING', 'ST_COLCODE', 'ST_COLDESC',
       'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR', 'COD_WEATHER',
       'COD_ROADCOND', 'COD_LIGHTCOND'],
      dtype='object')

In [33]:
y_data = np.asarray(data['SEVERITYCODE'])
X_data = np.asarray(data[['COD_WEATHER', 'COD_ROADCOND', 'COD_LIGHTCOND']])
X_data

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1],
       ...,
       [3, 2, 1],
       [3, 2, 5],
       [3, 1, 1]], dtype=int64)

In [34]:
X_data = preprocessing.StandardScaler().fit(X_data).transform(X_data)
X[0:5]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([['Overcast', 'Wet', 'Daylight'],
       ['Raining', 'Wet', 'Dark - Street Lights On'],
       ['Overcast', 'Dry', 'Daylight'],
       ['Clear', 'Dry', 'Daylight'],
       ['Raining', 'Wet', 'Daylight']], dtype=object)

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X_data,y_data,test_size=0.3,random_state=1)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (136271, 3) (136271,)
Test set: (58402, 3) (58402,)


K-Nearest Neighbours

In [16]:
from sklearn.neighbors import KNeighborsClassifier
k = 25
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=25, p=2,
           weights='uniform')

In [17]:
yhat_KNN = neigh.predict(X_test)
yhat_KNN[0:5]

array([2, 1, 1, 1, 1], dtype=int64)

Decision Tree

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
modelTree = DecisionTreeClassifier(criterion="entropy", max_depth = 7)

In [21]:
modelTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [23]:
yhat_Tree = modelTree.predict(X_test)
print (yhat_Tree[0:5])
print (y_test[0:5])

[1 1 1 1 1]
[1 2 1 1 1]


In [ ]:
Linear Regression

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
yhat_LR = LR.predict(X_test)
yhat_LR[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [39]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob[0:5]

array([[0.67653542, 0.32346458],
       [0.68874818, 0.31125182],
       [0.79909563, 0.20090437],
       [0.79011309, 0.20988691],
       [0.6485007 , 0.3514993 ]])

EVALUATION

In [44]:
print("Test set Accuracy KNN: ", jaccard_similarity_score(y_test, yhat_KNN))
print("Test set Accuracy Decision Tree: ", jaccard_similarity_score(y_test, yhat_Tree))
print("Test set Accuracy Logistic Regression: ", jaccard_similarity_score(y_test, yhat_LR))

Test set Accuracy KNN:  0.6775795349474333
Test set Accuracy Decision Tree:  0.7035546727851786
Test set Accuracy Logistic Regression:  0.7035889181877333


In [46]:
from sklearn.metrics import f1_score
print("Test set Accuracy KNN: ", f1_score(y_test, yhat_KNN, average='weighted'))
print("Test set Accuracy Decision Tree: ", f1_score(y_test, yhat_Tree, average='weighted'))
print("Test set Accuracy Logistic Regression: ", f1_score(y_test, yhat_LR, average='weighted'))

Test set Accuracy KNN:  0.6020200315663403
Test set Accuracy Decision Tree:  0.5812169162502522
Test set Accuracy Logistic Regression:  0.58116997652603


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
